import {useEffect,useState} from 'react';
import {apiRequest} from '@/lib/connection';
import type {SearchStatus} from '@/lib/seller-photos';

type Props={connected:boolean;initialStatus?:SearchStatus|null;disabled?:boolean;onStatusChange?:(status:SearchStatus)=>void;onBusy?:(busy:boolean)=>void};
export default function PhotoSearchSettings({connected,initialStatus,disabled=false,onStatusChange,onBusy}:Props){
  const [status,setStatus]=useState<SearchStatus|null>(initialStatus??null),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{let active=true;if(connected&&!initialStatus)void apiRequest<SearchStatus>('sellerStatus').then(value=>{if(active)setStatus(value);}).catch(()=>{if(active)setError('Photo search settings could not be loaded. Reload to try again.');});return()=>{active=false;};},[connected,initialStatus]);
  async function save(remove=false){setBusy(true);onBusy?.(true);setError('');setMessage('');try{const next=await apiRequest<SearchStatus>('sellerKey',{key:remove?'':key.trim()});setStatus(next);setKey('');setMessage(remove?'Automatic search disconnected. You can still use Google Lens.':'Seller-photo search is connected. You can now find seller photos.');onStatusChange?.(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy?.(false);}}
  return <section className="settings-panel connection-panel photo-search-settings"><h2>Seller-photo search</h2><p>Find store photos of your clothes, then confirm the exact design and color. No AI account needed.</p>{!connected?<p>Connect your wardrobe in Preferences to enable automatic search. You can use Google Lens and upload a seller photo here without connecting.</p>:<><p className="search-connection-status">{status?.configured?`Connected · ${status.used} of ${status.limit} monthly searches used in WearNext`:'Connect a free SerpApi account to search from your photos.'}</p><p className="small">Search sends a resized copy of the photo to SerpApi and Google Lens. Your search key is kept in your private Google backend. WearNext stops at 250 searches each month.</p><form onSubmit={event=>{event.preventDefault();void save();}}><label className="field"><span>{status?.configured?'Replace search key':'SerpApi search key'}</span><input type="password" value={key} onChange={event=>setKey(event.target.value)} autoComplete="off" spellCheck={false} autoCapitalize="none" placeholder="Paste your key from SerpApi" minLength={64} maxLength={64} required disabled={disabled||busy}/></label><div className="photo-picker-actions"><button className="primary" disabled={disabled||busy||!key.trim()}>{busy?'Checking…':'Connect photo search'}</button><a className="secondary" href="https://serpapi.com/manage-api-key" target="_blank" rel="noreferrer">Get a search key</a>{status?.configured&&<button className="quiet" type="button" disabled={disabled||busy} onClick={()=>void save(true)}>Disconnect search</button>}</div></form>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</>}<p className="small">Without a search key, use Google Lens and upload the seller photo you find. Choose the provider’s free plan; this app never upgrades your plan.</p></section>;
}
